### PR TITLE
Addressed Issues #21 and #31

### PR DESCRIPTION
**Pull request by temiyemi**
Syllable breakdown is no longer a required field to submit a name entry; Link to edit name now works from search results.

### CODE REVIEW

**Comment by temiyemi** [comment]
My guess is: it’s missing semi colons at the end of each line. It’s really not my style to add ; everywhere, but I know that breaks in grunt builds.

I can’t fix this right away, except maybe you know of a tool that can help rewrite the js file?

**Comment by temiyemi** [comment]
My bad! I thought this was logged on the website repo. Ok, will check.

**Comment by temiyemi** [comment]
Check again @dadepo <https://github.com/dadepo> I just made some changes. Turns out it’s the ;s.

**Comment by dadepo** [comment]
Everything is fine now! Merged

**Comment by temiyemi** [comment]
How do I update my update my fork to avoid conflict going forward? Or no need?

**Comment by dadepo** [comment]
You know, I was curious about this. I think there were changes to the main branch, after you branched off, which resulted to the conflict. I think something that could help is to continually update your branch with the main branch.

**Comment by temiyemi** [comment]
This should come in handy for others: https://help.github.com/articles/syncing-a-fork/ <https://help.github.com/articles/syncing-a-fork/>

**Pull request merged**
